### ISSUE TITLE
Roadmap / release plan?

### ISSUE THREAD

**Issue by catetrai** [moloney/dcm#11]
Hello,

thank you for creating this awesome tool. I feel like it plugs in lots of features that are missing from pynetdicom (perhaps rightfully so because out of scope), like abstractions centered on typical use cases, async operations, etc.

Since I am considering to incorporate the tool in our lab's analysis pipelines, it would help to know the following:

1. Do you have an estimate on the project's status, whether it will be maintained in the near future?
2. Are there any plans to release the package on some official channel (pypi, conda)? This would help with keeping track of versions and updates.
3. Do you have any preferences for how this tool should be cited?

**Comment by moloney** [comment]
Hi,

Glad to hear you are finding the code useful.   My plans are to continue to develop the code to meet my own needs, and if folks create high quality PRs that meet their needs (without disrupting my use cases) then I will take the time to review and merge those. Beyond that I can't really promise much.  I do use this at my job for a number of tasks and will continue to in the foreseeable future, so it is pretty unlikely the code will be abandoned in the near term.

I do want to get this available on pypi soon (maybe after merging the "QR Repo" PR), although since it is pure Python it isn't too hard to install straight from Github. 

I don't have any preference on how to site this tool, and don't currently plan any publication on it.

**Comment by catetrai** [comment]
Hi,

sorry for the late reply. I appreciate the feedback! Looking forward to the pypi release.

In case we end up using your library in any code for publication, I will make sure to reference the link to the repo at the specific commit we used.

Thank you again, I will close this issue.
