### ISSUE TITLE
dcm not compatible with Python v3.9.7

### ISSUE THREAD

**Issue by spaenigs** [moloney/dcm#4]
Running the example with Python 3.9.7 throws the following error: 

TypeError: DcmNode() takes no arguments

However, with version 3.7.11 it works as expected.

**Comment by moloney** [comment]
This looks to be due to a CPython bug introduced in 3.9.7 and fixed in 3.9.8: https://bugs.python.org/issue45081

Considering the limited impact (unless 3.9.7 is the default somewhere common?) and the fact that I use Protocol quite a bit in the code, I don't think it is worth it to try to work around the issue.
